Increase warning date for single servers BSP
hmcts/cnp-jenkins-library pull request #1221
Opened 2024-04-02 13:05 UTC by joshblackmoor

Notes:
* Increased date for single server warning for BSP so pipeline runs, we are in the process of deleting single servers now as migration is complete in prod.

2024-04-02 13:09 UTC, thomast1906 requested changes
You are increasing date for all the repos - is that needed?

2024-04-02 13:13 UTC, joshblackmoor commented
> You are increasing date for all the repos - is that needed?

Have split BSP into its own for date

2024-04-02 13:18 UTC, amstevenson approved these changes

2024-04-03 09:33 UTC, thomast1906 approved these changes

2024-04-03 09:36 UTC, merged