Bump minimum Java chart version
hmcts/cnp-jenkins-library pull request #804
Opened 2022-02-15 16:01 UTC by reespozzi

New chart release increases the startup period for pods to stop them failing to come up in prod when a HR has been deleted / rolled back.

2022-02-15 16:20 UTC, timja approved these changes

2022-02-21 13:34 UTC, timja requested changes
Please update the date to add another 2 weeks on given the short notice bump.
https://github.com/hmcts/cnp-jenkins-library/blob/master/vars/warnAboutDeprecatedChartConfig.groovy#L26

Also prob best to hold off and bump the node.js version too, see https://hmcts-reform.slack.com/archives/G01E6GKRKAM/p1645449797140479

2022-02-28 14:29 UTC, timja commented
@reespozzi  reminder

2022-02-28 14:35 UTC, reespozzi reviewed
Will bump date to two weeks from today in next commit

2022-02-28 14:58 UTC, timja commented on resources/uk/gov/hmcts/helm/check-deprecated-charts.sh
> +MIN_JAVA_VERSION="3.7.1"
```suggestion
MIN_JAVA_VERSION="3.7.2"
```

2022-02-28 14:59 UTC, timja approved these changes

2022-02-28 15:27 UTC, merged