Different method to check if PR before adding lock
hmcts/cnp-jenkins-library pull request #820
Opened 2022-03-07 15:54 UTC by reespozzi

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)
Trying alternative to https://github.com/hmcts/cnp-jenkins-library/pull/819.
Notes:
*
*
*

2022-03-07 16:00 UTC, njrich28 requested changes

2022-03-07 16:00 UTC, njrich28 commented on vars/sectionDeployToAKS.groovy
> +  def isPR = false
Can remove this with the suggested change below

2022-03-07 16:04 UTC, njrich28 commented on vars/sectionDeployToAKS.groovy
> +        }
Should extract this out as a function to avoid the direct duplication below

2022-03-08 13:07 UTC, reespozzi commented
https://github.com/hmcts/cnp-jenkins-library/pull/821

2022-03-08 13:07 UTC, closed without merging