Dtspo 9278 jenkins library update
hmcts/cnp-jenkins-library pull request #870
Opened 2022-07-13 14:43 UTC by reespozzi

https://tools.hmcts.net/jira/browse/DTSPO-9278
Update jenkins library to set global disableTraefikTls flag options based on what's passed through flux. Eg. for sds - https://github.com/hmcts/sds-flux-config/pull/2042

Tested this library against multiple places, see inside DTSPO ticket for pipelines

Notes:
*
*
*

2022-07-14 08:28 UTC, adusumillipraveen submitted a review, later dismissed

2022-07-14 09:18 UTC, timja requested changes
I would think about renaming the flag in a new version as the disable is a bit confusing given it's off my default.

`enableTraefikTls=true` would be clearer or `tls=true`

or
`ingress.tls.enabled=true`

2022-07-14 09:18 UTC, timja commented on vars/helmInstall.groovy
> +
this is not correct, why would you set an env value that would break all installs?
```suggestion
```

2022-07-14 09:18 UTC, timja commented on vars/helmInstall.groovy
>        "--namespace ${namespace}"
```suggestion
      "--set global.disableTraefikTls=false",
      "--namespace ${namespace}"
```

2022-07-18 13:43 UTC, adusumillipraveen approved these changes

2022-07-18 13:45 UTC, merged