added yarnv3 nagger deprication warning
hmcts/cnp-jenkins-library pull request #967
Opened 2023-01-17 11:01 UTC by narinder17

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

[dtspo-10794](https://tools.hmcts.net/jira/browse/DTSPO-10974) - adding a nagger warning to advise users to upgrade to yarnV3.

2023-01-17 11:05 UTC, timja commented on src/uk/gov/hmcts/contino/YarnBuilder.groovy
> +       WarningCollector.addPipelineWarning("packageManager required", "Please upgrade to Yarn V3 by adding packageManager to package.json. For examples see: https://github.com/hmcts/cnp-plum-frontend
better if you can send a pull request suggestion for upgrading or pointing to the slack announcement  https://moj.enterprise.slack.com/files/T1L0WSW9F/F04784SLAJC?origin_team=T1L0WSW9F
```suggestion
       WarningCollector.addPipelineWarning("old_yarn_version", "Please upgrade to Yarn V3 by adding packageManager to package.json. For examples see: https://github.com/hmcts/cnp-plum-frontend/blob/2bfb6eac580c0965e331731496619c0b5920d596/package.json#L47 and https://github.com/hmcts/dtsse-ardoq-adapter", LocalDate.of(2023, 03, 10 ))
```

2023-01-17 13:53 UTC, timja commented on src/uk/gov/hmcts/contino/YarnBuilder.groovy
> +       WarningCollector.addPipelineWarning("old_yarn_version", "Please upgrade to Yarn V3 by adding packageManager to package.json. For examples see: https://github.com/hmcts/cnp-plum-frontend/blob/2
Please improve the message, e.g
```suggestion
       WarningCollector.addPipelineWarning("old_yarn_version", "Please upgrade to Yarn V3, see https://moj.enterprise.slack.com/files/T1L0WSW9F/F04784SLAJC?origin_team=T1L0WSW9F", LocalDate.of(2023, 03, 10 ))
```

2023-01-18 09:51 UTC, timja approved these changes

2023-01-18 11:34 UTC, timja commented on .vscode/settings.json
> +}
Please remove

2023-01-18 11:52 UTC, narinder17 commented on .vscode/settings.json
> +}
folder removed as requested.

2023-01-18 11:56 UTC, timja requested changes
you need to call the nagger from somewhere. Please add links to where this has been tested and any slack messages

2023-01-18 11:56 UTC, timja commented on src/uk/gov/hmcts/contino/YarnBuilder.groovy
> +  private yarnDepreciationCheck() {
```suggestion
  private nagAboutOldYarnVersions() {
```

2023-01-20 09:24 UTC, timja commented on src/uk/gov/hmcts/contino/YarnBuilder.groovy
> +
```suggestion
    super.setupToolVersion()
    nagAboutOldYarnVersions()

```

2023-01-24 15:58 UTC, timja reviewed
Links to testing? Including builds and slack messages.

(FYI I'm going on leave for two weeks so feel free to get someone else to approve if all is working, the code looks good to me)

2023-01-26 10:09 UTC, narinder17 commented
The nagger error messages appears and runs fine in Jenkins library, shows error in cnp-plum-frontend repo. The build fails due to other dependancies in the cnp-plum-frontend repo, however this branch will not be merged and was used to point at https://github.com/hmcts/cnp-jenkins-library/pull/967 build.

https://tools.hmcts.net/jira/browse/DTSPO-10974

![image](https://user-images.githubusercontent.com/65078848/214809576-2ef4b896-f762-4d23-8ae5-218016d420b6.png)

<img width="701" alt="image" src="https://user-images.githubusercontent.com/65078848/214809649-fb2b6767-83aa-4989-ac10-c77cbedb3423.png">

Please upgrade to Yarn V3, see [https://moj.enterprise.slack.com/files/T1L0WSW9F/F04784SLAJC?origin_team=T1L0WSW9F](https://moj.enterprise.slack.com/files/T1L0WSW9F/F04784SLAJC?origin_team=T1L0WSW9F&origin_channel=D04KECS7690) This configuration will stop working by 10/03/2023 ( in 44 days )

2023-01-26 10:28 UTC, thomast1906 approved these changes

2023-01-26 15:11 UTC, thomast1906 approved these changes

2023-01-26 15:13 UTC, merged